name: Deploy

on:
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    env:
      CONTAINER_APP_SERVICE: "app"
      CONTAINER_DIST: "/project/dist"
      CONTAINER_USER: "node"
      HOST_DIST: "./dist"
    steps:
      - name: Setup GitHub Pages
        id: configure_pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Build Docker image
        run: docker compose build ${{ env.CONTAINER_APP_SERVICE }}
      - name: Perform quality checks and build artifacts
        run: |
          docker compose up -d ${{ env.CONTAINER_APP_SERVICE }}
          # quality check
          docker compose exec -u "${{ env.CONTAINER_USER }}" ${{ env.CONTAINER_APP_SERVICE }} npx tsc
          docker compose exec -u "${{ env.CONTAINER_USER }}" ${{ env.CONTAINER_APP_SERVICE }} npx oxlint
          docker compose exec -u "${{ env.CONTAINER_USER }}" ${{ env.CONTAINER_APP_SERVICE }} npx oxfmt --check
          # build artifacts
          docker compose exec -u "${{ env.CONTAINER_USER }}" ${{ env.CONTAINER_APP_SERVICE }} npx \
            vite build \
            --emptyOutDir \
            --outDir=${{ env.CONTAINER_DIST }} \
            --base=${{ steps.configure_pages.outputs.base_path }}
          CONTAINER_ID=$(docker compose ps -q ${{ env.CONTAINER_APP_SERVICE }})
          docker cp "${CONTAINER_ID}:${{ env.CONTAINER_DIST }}" "${{ env.HOST_DIST }}"
          docker compose down
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ${{ env.HOST_DIST }}
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
